[package]
name = "code-signal"
version = "0.1.0"
authors = ["Jay Cunningham <j@crosscompiled.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
test-case = "1.1.0"
